### PR TITLE
Bug/decode ascii entity

### LINKED ISSUE #19: Getting error 404 on a file because of charset
https://cyberdrop.me/a/C7zLRzOw

Third file is getting an error because of the ' in the name. The charset used in the app convert the ' to &39; therefore the app says the file does not exist.

Sophie Mudd Reese's RAW.mp4
See screenshot for app error and how it is outputting on the app.

Windows 10 Pro (in French obviously)
Cy-client 1.1.3

error404

### PR DESCRIPTION
**Pull request by izqalan**
closes #19

### CODE REVIEW

File: cyberdropDownloader/CyScraper.cs [hunk 1]
```diff
@@ -52,7 +52,7 @@ public string CheckIllegalChars(string s)
             string regexSearch = new string(Path.GetInvalidFileNameChars()) + new string(Path.GetInvalidPathChars());
             Regex r = new Regex(string.Format("[{0}]", Regex.Escape(regexSearch)));
             s = r.Replace(s, "");
-            s = s.Length == 0 ? "cy_album" : s; 
+            s = s.Length == 0 ? "cy_album" : Mono.Web.HttpUtility.HtmlDecode(s); ;
```
Comment (izqalan) [inline cyberdropDownloader/CyScraper.cs:55]: TIL this compiles
